# Generated by Django 2.2.2 on 2021-07-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.IntegerField(unique=True)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('IT', 'it'), ('CSE', 'cse'), ('ECE', 'ece'), ('CE', 'ce'), ('MECH', 'mech')], max_length=15)),
                ('published_in', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
